all : A B C D E F

A : problemA.cpp
	g++ -ggdb -o A problemA.cpp

B : problemB.cpp
	g++ -ggdb -o B problemB.cpp

C : problemC.cpp
	g++ -ggdb -o C problemC.cpp

D : problemD.cpp
	g++ -ggdb -o D problemD.cpp

E : problemE.cpp
	g++ -ggdb -o E problemE.cpp

F : problemF.cpp
	g++ -ggdb -o F problemF.cpp

G : problemG.cpp
	g++ -ggdb -o G problemG.cpp

H : problemH.cpp
	g++ -ggdb -o H problemH.cpp

I : problemI.cpp
	g++ -ggdb -o I problemI.cpp

J : problemJ.cpp
	g++ -ggdb -o J problemJ.cpp

clean :
	rm A B C D E F G H I J
