all : A B C D E F

A : problemA.cpp
	g++ -ggdb -o A problemA.cpp

B : problemB.cpp
	g++ -ggdb -o B problemB.cpp

C : problemC.cpp
	g++ -ggdb -o C problemC.cpp

D : problemD.cpp
	g++ -ggdb -o D problemD.cpp

E : problemE.cpp
	g++ -ggdb -o E problemE.cpp

F : problemF.cpp
	g++ -ggdb -o F problemF.cpp

clean :
	rm -f A B C D E F
